### ISSUE TITLE
Crash when open camera on android 

### ISSUE THREAD

**Issue by pikooli** [leegeunhyeok/react-native-zendesk-messaging#15]
Hello, thanks you for this library.

I implement it on my app but I got a issue in android when i try to take a picture and send it to the support.

I just crash the app. 

I did add the implementation on the AndroidManifest,  build.gradle ...

Everything work excepted that i cannot open the camera.

My app use the camera to make video call, so I have the autorisation.

Any idea on this issues ? 

<img width="749" alt="Capture d’écran 2023-05-16 à 17 35 06" src="https://github.com/leegeunhyeok/react-native-zendesk-messaging/assets/53048735/155c3d2c-87dc-4319-8b04-e5ce8cd05fbd">

<img width="359" alt="Capture d’écran 2023-05-16 à 17 33 30" src="https://github.com/leegeunhyeok/react-native-zendesk-messaging/assets/53048735/7dd61f43-f506-40c5-97c0-0275b248133a">

**Comment by leegeunhyeok** [comment]
@pikooli My application is works fine on real device and emulator.

Can you share any crash log?

**Comment by pikooli** [comment]
Hello sorry for the delay.

I try to upgrade the sdk version to "2.11.0" and I don't see the crash anymore :) 

Thanks you for helping

**Comment by pikooli** [comment]
How do you get the crash report ? 
Can you have crash report without any library ? 
With metro maybe ?

**Comment by leegeunhyeok** [comment]
@pikooli you can get crash log from Logcat.
In production, you can get crash report using Firebase crashlytics, Sentry and others.

**Comment by leegeunhyeok** [comment]
If this issue still not resolved yet, please reopen issue :)
