### ISSUE TITLE
iOS: Update Push Notification Token

### ISSUE THREAD

**Issue by KarthikBhaskara** [leegeunhyeok/react-native-zendesk-messaging#19]
**Describe the bug**
I noticed that the `updatePushNotificationToken` method is a no-op for non-Android devices.

I'm curious why this us since I see the method defined in the `ios/ZendeskNativeModule.swift`.

**Comment by leegeunhyeok** [comment]
`updatePushNotificationToken` method is for integrate with third-part push notification libraries (eg. [@react-native-firebase/messaging](https://rnfirebase.io/reference/messaging)). (currently, support Android only)

Zendesk messaging SDK uses FCM token on Android, APNs token on iOS for notifications
FCM token is string type, but APNs device token isn't (NSData).

In iOS React Native native bridge, NSData type is not supported ([docs](https://reactnative.dev/docs/native-modules-ios#argument-types)).
This means the serialization required(eg. NSData to NSString) before communicating with the native and JS sides.

This is why `updatePushNotificationToken` don't supported on iOS and need to setup in native.

In `ZendeskNativeModule.swift`, `updatePushNotificationToken` method already implemented but it is for use in native (AppDelegate)

In additional, there are a few ways to get the APNs token from JS via library,

- [@react-native-firebase/messaging](https://rnfirebase.io/reference/messaging): `getAPNSToken()` (string)
- [react-native-push-notification-ios](https://github.com/react-native-push-notification/ios): register event (string)

These libraries also serialize token in native code.

Need to implement serialization for using `updatePushNotificationToken` in iOS, but is not planned yet.
