### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 3): Error: Zendesk failed to initialize.

### ISSUE THREAD

**Issue by jyear** [leegeunhyeok/react-native-zendesk-messaging#20]
Possible Unhandled Promise Rejection (id: 3):
Error: Zendesk failed to initialize.

**Comment by jyear** [comment]
当我在react-native0.69.12  安卓上使用得时候   初始化失败
Possible Unhandled Promise Rejection (id: 3):
Error: Zendesk failed to initialize.

**Comment by leegeunhyeok** [comment]
@jyear Can you share your code?

You should handle initialize() and check error reason.

```ts
Zendesk.initialize(...).catch((error) => {
  console.log(error); // << error reason here!
});
```

**Comment by leegeunhyeok** [comment]
Can you add this configuration on native and check crash logs? @jyear

Android: https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/getting_started/#logging
iOS: https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/ios/getting_started/#troubleshooting

**Comment by singhagam1** [comment]
I tried enabling the debug log but no help, same javascript logs  showing up in xcode.
Question - will the same channelid that is used in the script tag appended after snippet.js?key=XXXXXX work or do we need to create another ?
