### ISSUE TITLE
Android build crash

### ISSUE THREAD

**Issue by uasghar-smile** [leegeunhyeok/react-native-zendesk-messaging#21]
**Android build crash**
I have installed this lib in iOS it's working fine but in Android getting build crash before run app successfully

**To Reproduce**
1. Run command 'yarn add react-native-zendesk-messaging'
2. Follow the steps to setup SDK natively for android from here 

- https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/docs/getting-started.md
- https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/getting_started/

3. compile the code and get error during build process
4. See error detail bellow in the attached screenshot

**Expected behavior**
App should compile successfully as it's happening for iOS.

**Screenshots**
<img width="1262" alt="Screenshot 2023-08-17 at 7 05 37 PM" src="https://github.com/leegeunhyeok/react-native-zendesk-messaging/assets/102786004/3daeb551-efc8-4bfc-8bc4-7de44b14edf4">

**Environment:**
 - Platform: [Android]
 - React Native Version 0.68.6
 - Zendesk SDK Version "react-native-zendesk-messaging": "^0.1.1",

**Comment by uasghar-smile** [comment]
Hi @leegeunhyeok please help me out. Thanks!

**Comment by leegeunhyeok** [comment]
@uasghar-smile What's your `compileSdkVersion` and `targetSdkVersion` in your app/build.gradle?

By default, `react-native-zendesk-messaging` is using Zendesk SDK [2.8.0](https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/v0.1.1/package.json#L93).
You should bump version up build sdk versions on gradle or downgrade Zendesk SDK.

https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/docs/getting-started.md#overriding-sdk-versions

**Comment by uasghar-smile** [comment]
@leegeunhyeok my  `compileSdkVersion` and `targetSdkVersion` versions is 33. I am not using the latest version of this lib which is `0.2.1` and my `react-native` version is `0.68.6`.
