### ISSUE TITLE
Reset Message History and Not Ask For Name

### ISSUE THREAD

**Issue by mhaslinsky** [leegeunhyeok/react-native-zendesk-messaging#22]
First of all, thank you for this. This is a wonderful tool.

Two things. 
1) is it possible to reset the chat history everytime the bot/app is opened. Currently it is retaining chat history and I don't see a way to stop it.
2) Is there a way to stop it for asking for the users name upon the first open?

**Comment by leegeunhyeok** [comment]
Hi, @mhaslinsky.

1. You cannot reset chat history programmatically, because that feature isn't implemented in the Zendesk SDK. (https://github.com/leegeunhyeok/react-native-zendesk-messaging/issues/18#issuecomment-1628682983)
2. You can setup custom bot flow on Zendesk dashboard.

**Comment by mhaslinsky** [comment]
I figured as much for 1, just wanted to make sure. I have no idea how I fixed 2 but, I did get it to stop.

**Comment by kfchan-git** [comment]
i did try to logout and re-intialize the chatbot, that can technically clear or reset history. (I'm not sure if this is the correct way, but feel free to correct me)
