### ISSUE TITLE
Support for conversation fields and tags

### ISSUE THREAD

**Issue by fikkatra** [leegeunhyeok/react-native-zendesk-messaging#25]
Thanks for this very useful wrapper! 
Question: do you plan to add support for conversation fields and tags in the near future? Cf. the [iOS](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/ios/advanced_integration/#conversation-fields) and [Android](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/advanced_integration/#conversation-fields) SDK documentation.

**Comment by leegeunhyeok** [comment]
Hi, @fikkatra.

Thank you for share new features.
I will start develop soon for support conversation fields and tags.

You can tracking task status [here](https://github.com/users/leegeunhyeok/projects/3/views/1) :)

**Comment by leegeunhyeok** [comment]
# Notes

Conversation fields and tags supported SDK version: 2.13.0

**Comment by leegeunhyeok** [comment]
Hi, @fikkatra.

Conversation fields and tags are now available on [0.2.0](https://github.com/leegeunhyeok/react-native-zendesk-messaging/releases/tag/v0.2.0). please check it out :)
