### ISSUE TITLE
[iOS] Exception: sendPageViewEvent:resolver is not a recognized Objective-C method

### ISSUE THREAD

**Issue by fikkatra** [leegeunhyeok/react-native-zendesk-messaging#28]
**Describe the bug**
When executing:

`Zendesk.sendPageViewEvent({ pageTitle: 'Dashboard', url: 'Dashboard' });`

on iOS, the following exception occurs:

Exception 'sendPageViewEvent:resolver is not a recognized Objective-C method.' was thrown while invoking sendPageViewEvent on target ZendeskMessaging with params (
        {
        pageTitle = Dashboard;
        url = Dashboard;
    },
    4846,
    4847
)

On Android, it works as intended.

**To Reproduce**
* Create react native app (v0.71.8)
* Setup react-native-zendesk-messaging library
* Start iOS Simulator
* Execute Zendesk.initialize => everything works fine, Zendesk.openMessagingView opens the chat window
* Execute Zendesk.sendPageViewEvent => exception is thrown

**Expected behavior**
Zendesk.sendPageViewEvent should not cause exception.

**Environment (please complete the following information):**
 - Platform: iOS
 - React Native: 0.71.8
 - react-native-zendesk-messaging: 0.1.1
 - Zendesk SDK Version: did not override SDK Version => as per the docs, the default 2.8.0 is used

**Additional context**
callstack: (
	0   CoreFoundation                      0x00000001804658a8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018005c09c objc_exception_throw + 56
	2   Foundation                          0x0000000180cf3b90 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
	3   MYAPPDEV                               0x00000001015cbf5c -[RCTModuleMethod processMethodSignature] + 832
	4   MYAPPDEV                               0x00000001015d230c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 144
	5   MYAPPDEV                               0x00000001015d688c _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1596
	6   MYAPPDEV                               0x00000001015d6084 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 128
	7   MYAPPDEV                               0x00000001015d5ff8 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	8   libdispatch.dylib                   0x00000001801424f4 _dispatch_call_block_and_release + 24
	9   libdispatch.dylib                   0x0000000180143d3c _dispatch_client_callout + 16
	10  libdispatch.dylib                   0x000000018014be3c _dispatch_lane_serial_drain + 960
	11  libdispatch.dylib                   0x000000018014c9b4 _dispatch_lane_invoke + 388
	12  libdispatch.dylib                   0x0000000180157d40 _dispatch_root_queue_drain_deferred_wlh + 276
	13  libdispatch.dylib                   0x000000018015738c _dispatch_workloop_worker_thread + 448
	14  libsystem_pthread.dylib             0x0000000106917878 _pthread_wqthread + 284
	15  libsystem_pthread.dylib             0x000000010691663c start_wqthread + 8
)

RCTFatal
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_root_queue_drain_deferred_wlh
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread

**Comment by leegeunhyeok** [comment]
Hi, @fikkatra.

This issue was fixed and release as `0.1.2`. Please update package.

https://github.com/leegeunhyeok/react-native-zendesk-messaging/releases/tag/v0.1.2
