### ISSUE TITLE
Cannot open Chat view on Android with proguard enabled

### ISSUE THREAD

**Issue by xuanmai-agilityio** [leegeunhyeok/react-native-zendesk-messaging#31]
**Describe the bug**
When I set `enableProguardInReleaseBuilds` to true, the app builds success but can't open the chat view.

**To Reproduce**
1. Go to `android/app/build.gradle`
2. Set `enableProguardInReleaseBuilds` to `true`
3. Build app in release mode again

**Expected behavior**
It should work as normal

**Environment (please complete the following information):**
 - Platform: [Android]
 - React Native Version [0.71.2]
 - Zendesk SDK Version [2.11.0]

**Comment by leegeunhyeok** [comment]
Add the [proguard configuration] and check it out?

**Comment by xuanmai-agilityio** [comment]
Just tried and it worked. Thanks for your support!
