### ISSUE TITLE
Android in release build ..... Zendesk not initialised.. missing field in qu.b

### ISSUE THREAD

**Issue by honey10597** [leegeunhyeok/react-native-zendesk-messaging#32]
![Screenshot 2023-10-06 at 7 30 49 PM](https://github.com/leegeunhyeok/react-native-zendesk-messaging/assets/42267565/e0f4b391-c613-4563-a215-0bc992c32ef1)

Android in release build ..... Zendesk not initialised in android release build.. missing field in qu.b.. In debug its working fine

**Comment by leegeunhyeok** [comment]
Which package or SDK version are you using?

Add the [proguard configuration](https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/docs/getting-started.md#known-issues) and check it out?
