### ISSUE TITLE
I am trying to run react-native-zendesk-messaging on Android and the application is crashing in release mode when progaurd is enabled.

### ISSUE THREAD

**Issue by anandsharmaautovyn** [leegeunhyeok/react-native-zendesk-messaging#36]
**Describe the bug**
when progaurd is enabled the application is crashing when calling method Zendesk.openMessagingView()

**To Reproduce**
1. Go to 'android\app\build.gradle'
2. Scroll down to 'minifyEnabled enableProguardInReleaseBuilds'
4. add shrinkResources true, minifyEnabled true
5. see the error when you make release build and open the messaging activity using Zendesk.openMessagingView()

**Expected behavior**
while these two `shrinkResources true, minifyEnabled true` are enabled the package should work as expected

**Screenshots**
It's just keeps crashing the app even after reopening the app

**Environment (please complete the following information):**
 - Platform: [Android]
 - React Native Version [0.72.3]
 - Zendesk SDK Version [2.13.0]

**Comment by anandsharmaautovyn** [comment]
@leegeunhyeok can you provide the progaurd rule file so that i can remove the package from progaurd

**Comment by anandsharmaautovyn** [comment]
@leegeunhyeok any update as the application needs to be live in 2-3 days please reply ASAP.

**Comment by leegeunhyeok** [comment]
@anandsharmaautovyn

Add proguard rule to your `proguard-rules.pro`

```
-keepnames class zendesk.** { *; }
```

[docs](https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/docs/getting-started.md#known-issues)

**Comment by anandsharmaautovyn** [comment]
@leegeunhyeok it is still crashing can you please check it again?

**Comment by leegeunhyeok** [comment]
Can I get any crash logs?

**Comment by anandsharmaautovyn** [comment]
I didn't know how to get them

**Comment by anandsharmaautovyn** [comment]
can you tell me any way to get them as the application is crashing (it doesn't launch at first) in debug build if I enable the progaurd

**Comment by leegeunhyeok** [comment]
Are you using a monitoring solution in your app? (eg. Sentry, Firebase Crashlytics)

Without logs, it's hard to know what the problem is
