### ISSUE TITLE
Update to latest SDK version

### ISSUE THREAD

**Issue by mfds** [leegeunhyeok/react-native-zendesk-messaging#39]
Hello 👋 

This library currently runs SDKs version [2.13.0 android](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/release_notes/#2130---2023-07-05) and [2.13.0 iOS](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/ios/release_notes/#2130---2023-07-06) which was released more than a year ago.

The current release is, at the time of writing, [2.18.0](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/ios/release_notes/#2180---2024-02-01).

It doesn't look like there are breaking changes between the two versions so, would it be possible to update the SDKs?

Many thanks
Michele Fiordispina

**Comment by mfds** [comment]
@leegeunhyeok would it be possible to do something about this?

**Comment by mfds** [comment]
Hey, this should be fixed by https://github.com/leegeunhyeok/react-native-zendesk-messaging/pull/46

**Comment by compwron** [comment]
I would also like this :)
