### ISSUE TITLE
Does not open saved conversations on IOS

### ISSUE THREAD

**Issue by ChiefDesigns** [leegeunhyeok/react-native-zendesk-messaging#41]
**Describe the bug**
This is observed on a chatbot channel.
When message view is opened using the openMessagingView method. A new view is opened and the chat bot is initiated. If you have previous conversations, when you open the message view again and see the previous conversations list. Clicking on any of the conversations in the list does not open the conversation.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the messaging view
2. Send a message to the chatbot.
3. Exit the message view. 
4. Close the zendesk chat (message view) all together
5. Open message view again to see the previous conversation list.
6. Pressing on any of the conversations on the list does not open the conversion to engage with the chatbot or view messages. User stays on the conversation list screen.

**Expected behaviour**
To be able to open existing conversations in the conversation list so that you can view the messages again. During investigation for this issue. Looked at the demo apps provided by zendesk for IOS, on running the application was able to go into the previous conversations in the list and open them to see the messages.

**Environment (please complete the following information):**
 - Platform: IOS 16.2 (Simulator) and IOS 17.2.1 (Physical device)
 - React Native Version 0.70.6, 0.72.1 
 - Zendesk SDK Version 2.1.0
 - ZendeskSDKMessaging 2.13.0 to 2.18.1 (Tried each and every version from the release notes)

**Comment by akumarclick** [comment]
@ChiefDesigns were you able to resolve it? How is it showing previous conversations list as its directly opening the chat view every time we call the openMessagingView method
