### ISSUE TITLE
Crash when proguard rules set to true

### ISSUE THREAD

**Issue by sayancitytech** [leegeunhyeok/react-native-zendesk-messaging#43]
if I set proguardrule set to false then after apk build it works.

As per your docs I have set proguard rules set to true and -keepnames class zendesk.** { *; }
the build apk will crash when I am launching the react-native-zendesk-messaging through a button call. 
In dev mode no issue is there.

    "react-native": "0.73.5",
    "react-native-zendesk-messaging": "^0.2.1",

console:

ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in D:\ADHD\ADHD360\android\app\build\outputs\mapping\release\missing_rules.txt.
ERROR: R8: Missing class com.google.firebase.messaging.FirebaseMessagingService (referenced from: void zendesk.messaging.android.push.DefaultMessagingService.<init>() and 1 other context)
Missing class com.google.firebase.messaging.RemoteMessage (referenced from: void zendesk.messaging.android.push.DefaultMessagingService.onMessageReceived(com.google.firebase.messaging.RemoteMessage))

I have added android.enableR8.fullMode=false in gradle.properties

proguard rules:

-keep class com.mypackage.BuildConfig { *; }
-keepnames class zendesk.** { *; }
-keep class zendesk.** { *; }
-keep class com.facebook.hermes.unicode.** { *; }
-keep class com.facebook.jni.** { *; }

Still no luck

**Comment by ivancheng1214** [comment]
@sayancitytech

Did you solve the app crash issue in android release build?
