### ISSUE TITLE
Zendesk sdk 2.19.0 breaks back button on Android

### ISSUE THREAD

**Issue by XantreDev** [leegeunhyeok/react-native-zendesk-messaging#47]
**Describe the bug**
When user taps on back button with `@react-navigation/stack` and `react-native-zendesk-messaging` installed application hides

**To Reproduce**
1. Install application
2. Go to some screen in stack
3. Try to use android go back button/gesture

**Expected behavior**
Application opened previous screen

**Screenshots**

https://github.com/leegeunhyeok/react-native-zendesk-messaging/assets/57757211/2afb0038-70f4-4f6b-8e2c-40fe9a34a079

**Environment (please complete the following information):**
 - Platform: Android
 - React Native Version 0.73.7
 - Zendesk SDK Version 2.19.0

**Additional context**
Fix
```
diff --git a/apps/international/android/build.gradle b/apps/international/android/build.gradle
index db88928e..5ab5df7f 100644
--- a/apps/international/android/build.gradle
+++ b/apps/international/android/build.gradle
@@ -23,7 +23,7 @@ buildscript {
         // mapbox end

         // Zendesk
-        zendeskSdkVersion = "2.19.0"
+        zendeskSdkVersion = "2.18.0"
         // Zendesk end
     }
     repositories {
```

**Comment by XantreDev** [comment]
bump

**Comment by ande-** [comment]
I'm having this same issue

**Comment by XantreDev** [comment]
Bump

**Comment by otech47** [comment]
still a problem. should be fixed
