### ISSUE TITLE
 iOS app launch get failed after zendesk messaging integration

### ISSUE THREAD

**Issue by lavanyaRamesh064** [leegeunhyeok/react-native-zendesk-messaging#5]
Facing below issue when tried to launch iOS app using xcode.

Unexpected token, expected "," in index.ts 

Installed 
Library : react-native-zendesk-messaging using yarn packager 
Version : 0.1.0

React-native version : 0.63.3
React version : 16.3.1

**Comment by leegeunhyeok** [comment]
Can I get more details? (for eg. error lines)

**Comment by lavanyaRamesh064** [comment]
On launching iOS app, I'm facing this issue under : 
/node_modules/react-native-zendesk-messaging/src/index.ts: 
Unexpected token, expected "," (5:7)

  3 |   NativeEventEmitter,
  4 |   Platform,
> 5 |   type EmitterSubscription,
    |        ^
  6 | } from 'react-native';

**Comment by leegeunhyeok** [comment]
@lavanyaRamesh064 Some problems with the environment configuration.

Go to `node_modules/react-native-zendesk-messaging/package.json` and change entry point like this:

```json
  "react-native": "lib/module/index",
```

then restart metro and check please.

**Comment by leegeunhyeok** [comment]
Which typescript version are you using?

**Comment by victorCS46** [comment]
> @lavanyaRamesh064 Some problems with the typescript environment configuration.
> 
> Go to `node_modules/react-native-zendesk-messaging/package.json` and change entry point like this:
> 
> ```json
>   "react-native": "lib/module/index",
> ```
> 
> then restart metro and check please.

This solution works for me. Will you be setting it in your next release?

**Comment by leegeunhyeok** [comment]
> > @lavanyaRamesh064 Some problems with the typescript environment configuration.
> > Go to `node_modules/react-native-zendesk-messaging/package.json` and change entry point like this:
> > ```json
> >   "react-native": "lib/module/index",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then restart metro and check please.
> 
> This solution works for me. Will you be setting it on your next release?

This changes will be apply to next patch version.

For resolve this issue temporary, please using [patch-package](https://www.npmjs.com/package/patch-package).

**Comment by leegeunhyeok** [comment]
It was fixed and released as [`react-native-zendesk-messaging@0.1.1`](https://github.com/leegeunhyeok/react-native-zendesk-messaging/releases/tag/v0.1.1)
