### ISSUE TITLE
iOS push notifications

### ISSUE THREAD

**Issue by deelo55** [leegeunhyeok/react-native-zendesk-messaging#50]
In the [push notification instructions](https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/docs/ios-push-notifications.md)
I'm not 100% clear but is this suggesting you need to modify the native code to get push notifications working?

**Comment by deelo55** [comment]
Is there a way to do this when using Expo without writing any native code?
For example, in Expo I can get the push token, and then call this to update Zendesk:
https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/docs/apis.md#updatepushnotificationtoken

**Comment by adilsaeed31** [comment]
Yes, you can do this functionality in the Expo, if you don't want to use native code, then try firebase/messaging, there is a code I'll share below with that you can get the Push Notifications in both platforms, but android for sure, in IOS I'm not 100% sure for the Expo. But if you have a bare react native project then you have to add the native code to the IOS side to get the notifications in the production release version app only.

`
import * as Zendesk from 'react-native-zendesk-messaging'

messaging().onMessage(async (remoteMessage: any) => {
      console.log(
        'A new message arrived! ',
        JSON.stringify(remoteMessage),
      )

      const responsibility = await Zendesk.handleNotification(
        remoteMessage.data,
      )

      switch (responsibility) {
        case 'MESSAGING_SHOULD_DISPLAY':
        case 'MESSAGING_SHOULD_NOT_DISPLAY':
          // remote message was handled by Zendesk SDK
          return

        case 'NOT_FROM_MESSAGING':
        default:
          break
      }
     } 
     `
