### ISSUE TITLE
IOS Push Notification not opening the Zendesk Messaging View Screen

### ISSUE THREAD

**Issue by adilsaeed31** [leegeunhyeok/react-native-zendesk-messaging#51]
**Describe the bug**
In iOS devices, a message push notification does not open the Zendesk Messaging View screen, but this functionality works fine in Android after tapping on the push notification.

**To Reproduce**
Receive a push notification on an IOS device and tap on it, it will open the app but will not open the Zendesk messaging view screen in iOS only.

**Expected behavior**
On Push Notification tap, this should open the messaging view screen of Zendesk, like in Android.

**Environment (please complete the following information):**
 - Platform: IOS 17.5
 - React Native Version 0.74
 - Zendesk SDK Version ^0.2.1

**Comment by avivdim** [comment]
@adilsaeed31 Hi, I had the same issue with this library and i fixed it. can you show your code in AppDelegate.m?

**Comment by dgrover-spotnana** [comment]
Hey @avivdim , we are facing the same issue, can you let us know how you fixed it ?

@leegeunhyeok , are you aware of this issue ?
