### ISSUE TITLE
iOS updatePushNotificationToken

### ISSUE THREAD

**Issue by deelo55** [leegeunhyeok/react-native-zendesk-messaging#54]
Any reason why iOS doesn't support updatePushNotificationToken?

https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/src/index.ts
```
export function updatePushNotificationToken(token: string): void {
  if (Platform.OS !== 'android') return;
  return ZendeskMessaging.updatePushNotificationToken(token);
}
```

It is supported in the native code:
https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/ios/ZendeskNativeModule.swift

```
  @objc(updatePushNotificationToken:)
  static func updatePushNotificationToken(_ token: Data) -> Void {
    PushNotifications.updatePushNotificationToken(token)
  }
```

**Comment by avivdim** [comment]
@deelo55 I don't really understand your question..on iOS you just need to add it on AppDelegate.m and it will work. // `AppDelegate.m` or `AppDelegate.mm`
#import <ZendeskNativeModule.h>

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [ZendeskNativeModule updatePushNotificationToken:deviceToken];
}

please tell me if it helped you
