### ISSUE TITLE
Getting Initialize failed warning when trying to initialize with channel id

### ISSUE THREAD

**Issue by sanaf1333** [leegeunhyeok/react-native-zendesk-messaging#56]
Getting Initialize failed warning when trying to initialize with channel id.

```
Zendesk.initialize({
      channelKey:
        'my channel id here',
    });
```
1. Install react-native-zendesk-messaging, import  * as Zendesk from react-native-zendesk-messaging
2. Initialize it with your ios channel id
3. build the app

**Expected behavior**
It should be initialized and open chat box

**Screenshots**
<img width="481" alt="image" src="https://github.com/user-attachments/assets/71565011-cefe-4e04-b1bd-088fdc387823">

**Environment (please complete the following information):**
 - Platform: ios
 - React Native Version "react-native": "0.74.2",
 - Zendesk SDK Version  "react-native-zendesk-messaging": "^0.2.1",

I have to deploy the app on Monday, i'll be grateful if you can help me resolve this issue asap. Thank you

**Comment by abo-rythm** [comment]
Reproducing as well, did not find any fixes so far.

**Comment by sanaf1333** [comment]
@leegeunhyeok please if you can help with this asap.

**Comment by sanaf1333** [comment]
> Reproducing as well, did not find any fixes so far.

Have you tried any other library?

**Comment by bennyszantar** [comment]
I also reproducing this @leegeunhyeok, could you take a look ?

**Comment by bennyszantar** [comment]
@sanaf1333 @abo-rythm I solved it, you need to crate separate channel for IOS/Android and use channel key shown there, do not reuse web channel and its key, its not going to work.
