### ISSUE TITLE
Android App may not comply with new Google Play Photo and Video Permissions policy

### ISSUE THREAD

**Issue by akumarclick** [leegeunhyeok/react-native-zendesk-messaging#58]
**Describe the bug**

-  I’m using the `react-native-zendesk-messaging` package, and we’ve noticed that our app may be violating the [new Google Play Photo and Video Permissions policy.](https://support.google.com/googleplay/android-developer/answer/14115180?sjid=3703408598823754737-AP).
- The package seems to request broad access to photos and videos, which might not comply with the recent changes in the policy. According to the updated policy, apps are required to use system pickers for accessing photos and videos, and broad access is only acceptable if there is a core use case.

**To Reproduce**

1. Integrate the react-native-zendesk-messaging package in an app.
2. Attempt to upload a photo or video using Zendesk’s messaging/chat feature.
3. Observe the app’s permissions request flow.

**Current behavior**
The package is requesting the broad storage permissions which can cause compliance issues with Google Play.

**Expected behavior**
The package should use Android's photo picker for any media access, rather than requesting broad storage permissions.

**Environment :**
 - Platform: Android
 - React Native Version:  0.72.14
 -  react-native-zendesk-messaging Version: 0.2.1 
 - Zendesk Android SDK Version being used in the package: 2.13.0

**Comment by akumarclick** [comment]
@leegeunhyeok : Can you please help me with this?

**Comment by avivdim** [comment]
@akumarclick Upgrading the Android SDK to the latest version in the build.gradle file should solve your issue

**Comment by akumarclick** [comment]
@avivdim : Thanks for the reply. Will Updating the version there solve my problem? Because I don't see any update in the release notes of Zendesk Android SDK regarding this change in their SDK.

**Comment by avivdim** [comment]
@akumarclick You're right, it’s not explicitly mentioned in their changelog. However, keep in mind that version 2.13.0 is quite old and doesn't even support Android 14. The SDK has likely fixed many issues since that version. The fix for file uploading mentioned in the 2.22.0 release could indeed be related to this, but I'm not entirely sure. Please let me know if upgrading to the latest version solved the issue for you.

**Comment by akumarclick** [comment]
@avivdim : Thanks!
It worked for me after I updated native SDK's in the package locally to the latest versions. Also Zendesk official support has also confirmed that their latest SDK's are in complete compliance with the Google Play policies.
